### ISSUE TITLE
Typescript ternary condition wrong formating.

### ISSUE THREAD

**Issue by Insadem** [richie0866/rbxm-suite#9]
This rbx-ts code:
```TS
let a = (true) ? 1 : 2;
```
Will compile to:
```LUA
local a = if true then 1 else 2
```
But, this will break entire code without any error message (probably formating issue).
I spent 6 hours to find this in my project, it's really frustrating.

**Comment by richie0866** [comment]
Emitting if-then-else expressions was feature introduced to roblox-ts in version 1.2.8, and is not caused by rbxm-suite.

You should downgrade to roblox-ts 1.2.7 if you need their old behavior of compiling to and/or.
